apiVersion: skaffold/v2beta14
kind: Config
build:
  artifacts:
  - image: ghcr.io/shipperizer/json-mock
    custom:
      buildCommand: ./buildx.sh
      dependencies:
        dockerfile:
          path: Dockerfile
  local:
    push: true
deploy: {}
